<?php

namespace App\Support;

final class IsoCountries
{
    /**
     * ISO 3166-1 alpha-2 => [English, Turkish]
     *
     * @return array<string, array{0: string, 1: string}>
     */
    public static function all(): array
    {
        return [
            'AD' => ['Andorra', 'Andorra'],
            'AE' => ['United Arab Emirates', 'Birleşik Arap Emirlikleri'],
            'AF' => ['Afghanistan', 'Afganistan'],
            'AG' => ['Antigua and Barbuda', 'Antigua ve Barbuda'],
            'AI' => ['Anguilla', 'Anguilla'],
            'AL' => ['Albania', 'Arnavutluk'],
            'AM' => ['Armenia', 'Ermenistan'],
            'AO' => ['Angola', 'Angola'],
            'AQ' => ['Antarctica', 'Antarktika'],
            'AR' => ['Argentina', 'Arjantin'],
            'AS' => ['American Samoa', 'Amerikan Samoası'],
            'AT' => ['Austria', 'Avusturya'],
            'AU' => ['Australia', 'Avustralya'],
            'AW' => ['Aruba', 'Aruba'],
            'AX' => ['Åland Islands', 'Åland Adaları'],
            'AZ' => ['Azerbaijan', 'Azerbaycan'],
            'BA' => ['Bosnia and Herzegovina', 'Bosna-Hersek'],
            'BB' => ['Barbados', 'Barbados'],
            'BD' => ['Bangladesh', 'Bangladeş'],
            'BE' => ['Belgium', 'Belçika'],
            'BF' => ['Burkina Faso', 'Burkina Faso'],
            'BG' => ['Bulgaria', 'Bulgaristan'],
            'BH' => ['Bahrain', 'Bahreyn'],
            'BI' => ['Burundi', 'Burundi'],
            'BJ' => ['Benin', 'Benin'],
            'BL' => ['Saint Barthélemy', 'Saint Barthélemy'],
            'BM' => ['Bermuda', 'Bermuda'],
            'BN' => ['Brunei', 'Brunei'],
            'BO' => ['Bolivia', 'Bolivya'],
            'BQ' => ['Caribbean Netherlands', 'Karayip Hollandası'],
            'BR' => ['Brazil', 'Brezilya'],
            'BS' => ['Bahamas', 'Bahamalar'],
            'BT' => ['Bhutan', 'Butan'],
            'BV' => ['Bouvet Island', 'Bouvet Adası'],
            'BW' => ['Botswana', 'Botsvana'],
            'BY' => ['Belarus', 'Belarus'],
            'BZ' => ['Belize', 'Belize'],
            'CA' => ['Canada', 'Kanada'],
            'CC' => ['Cocos Islands', 'Cocos Adaları'],
            'CD' => ['DR Congo', 'Kongo DC'],
            'CF' => ['Central African Republic', 'Orta Afrika Cumhuriyeti'],
            'CG' => ['Congo', 'Kongo'],
            'CH' => ['Switzerland', 'İsviçre'],
            'CI' => ['Côte d’Ivoire', 'Fildişi Sahili'],
            'CK' => ['Cook Islands', 'Cook Adaları'],
            'CL' => ['Chile', 'Şili'],
            'CM' => ['Cameroon', 'Kamerun'],
            'CN' => ['China', 'Çin'],
            'CO' => ['Colombia', 'Kolombiya'],
            'CR' => ['Costa Rica', 'Kosta Rika'],
            'CU' => ['Cuba', 'Küba'],
            'CV' => ['Cabo Verde', 'Yeşil Burun'],
            'CW' => ['Curaçao', 'Curaçao'],
            'CX' => ['Christmas Island', 'Christmas Adası'],
            'CY' => ['Cyprus', 'Kıbrıs'],
            'CZ' => ['Czechia', 'Çekya'],
            'DE' => ['Germany', 'Almanya'],
            'DJ' => ['Djibouti', 'Cibuti'],
            'DK' => ['Denmark', 'Danimarka'],
            'DM' => ['Dominica', 'Dominika'],
            'DO' => ['Dominican Republic', 'Dominik Cumhuriyeti'],
            'DZ' => ['Algeria', 'Cezayir'],
            'EC' => ['Ecuador', 'Ekvador'],
            'EE' => ['Estonia', 'Estonya'],
            'EG' => ['Egypt', 'Mısır'],
            'EH' => ['Western Sahara', 'Batı Sahra'],
            'ER' => ['Eritrea', 'Eritre'],
            'ES' => ['Spain', 'İspanya'],
            'ET' => ['Ethiopia', 'Etiyopya'],
            'FI' => ['Finland', 'Finlandiya'],
            'FJ' => ['Fiji', 'Fiji'],
            'FK' => ['Falkland Islands', 'Falkland Adaları'],
            'FM' => ['Micronesia', 'Mikronezya'],
            'FO' => ['Faroe Islands', 'Faroe Adaları'],
            'FR' => ['France', 'Fransa'],
            'GA' => ['Gabon', 'Gabon'],
            'GB' => ['United Kingdom', 'Birleşik Krallık'],
            'GD' => ['Grenada', 'Grenada'],
            'GE' => ['Georgia', 'Gürcistan'],
            'GF' => ['French Guiana', 'Fransız Guyanası'],
            'GG' => ['Guernsey', 'Guernsey'],
            'GH' => ['Ghana', 'Gana'],
            'GI' => ['Gibraltar', 'Cebelitarık'],
            'GL' => ['Greenland', 'Grönland'],
            'GM' => ['Gambia', 'Gambiya'],
            'GN' => ['Guinea', 'Gine'],
            'GP' => ['Guadeloupe', 'Guadeloupe'],
            'GQ' => ['Equatorial Guinea', 'Ekvator Ginesi'],
            'GR' => ['Greece', 'Yunanistan'],
            'GS' => ['South Georgia', 'Güney Georgia'],
            'GT' => ['Guatemala', 'Guatemala'],
            'GU' => ['Guam', 'Guam'],
            'GW' => ['Guinea-Bissau', 'Gine-Bissau'],
            'GY' => ['Guyana', 'Guyana'],
            'HK' => ['Hong Kong', 'Hong Kong'],
            'HM' => ['Heard Island', 'Heard Adası'],
            'HN' => ['Honduras', 'Honduras'],
            'HR' => ['Croatia', 'Hırvatistan'],
            'HT' => ['Haiti', 'Haiti'],
            'HU' => ['Hungary', 'Macaristan'],
            'ID' => ['Indonesia', 'Endonezya'],
            'IE' => ['Ireland', 'İrlanda'],
            'IL' => ['Israel', 'İsrail'],
            'IM' => ['Isle of Man', 'Man Adası'],
            'IN' => ['India', 'Hindistan'],
            'IO' => ['British Indian Ocean Territory', 'Britanya Hint Okyanusu Toprakları'],
            'IQ' => ['Iraq', 'Irak'],
            'IR' => ['Iran', 'İran'],
            'IS' => ['Iceland', 'İzlanda'],
            'IT' => ['Italy', 'İtalya'],
            'JE' => ['Jersey', 'Jersey'],
            'JM' => ['Jamaica', 'Jamaika'],
            'JO' => ['Jordan', 'Ürdün'],
            'JP' => ['Japan', 'Japonya'],
            'KE' => ['Kenya', 'Kenya'],
            'KG' => ['Kyrgyzstan', 'Kırgızistan'],
            'KH' => ['Cambodia', 'Kamboçya'],
            'KI' => ['Kiribati', 'Kiribati'],
            'KM' => ['Comoros', 'Komorlar'],
            'KN' => ['Saint Kitts and Nevis', 'Saint Kitts ve Nevis'],
            'KP' => ['North Korea', 'Kuzey Kore'],
            'KR' => ['South Korea', 'Güney Kore'],
            'KW' => ['Kuwait', 'Kuveyt'],
            'KY' => ['Cayman Islands', 'Cayman Adaları'],
            'KZ' => ['Kazakhstan', 'Kazakistan'],
            'LA' => ['Laos', 'Laos'],
            'LB' => ['Lebanon', 'Lübnan'],
            'LC' => ['Saint Lucia', 'Saint Lucia'],
            'LI' => ['Liechtenstein', 'Liechtenstein'],
            'LK' => ['Sri Lanka', 'Sri Lanka'],
            'LR' => ['Liberia', 'Liberya'],
            'LS' => ['Lesotho', 'Lesotho'],
            'LT' => ['Lithuania', 'Litvanya'],
            'LU' => ['Luxembourg', 'Lüksemburg'],
            'LV' => ['Latvia', 'Letonya'],
            'LY' => ['Libya', 'Libya'],
            'MA' => ['Morocco', 'Fas'],
            'MC' => ['Monaco', 'Monako'],
            'MD' => ['Moldova', 'Moldova'],
            'ME' => ['Montenegro', 'Karadağ'],
            'MF' => ['Saint Martin', 'Saint Martin'],
            'MG' => ['Madagascar', 'Madagaskar'],
            'MH' => ['Marshall Islands', 'Marshall Adaları'],
            'MK' => ['North Macedonia', 'Kuzey Makedonya'],
            'ML' => ['Mali', 'Mali'],
            'MM' => ['Myanmar', 'Myanmar'],
            'MN' => ['Mongolia', 'Moğolistan'],
            'MO' => ['Macao', 'Makao'],
            'MP' => ['Northern Mariana Islands', 'Kuzey Mariana Adaları'],
            'MQ' => ['Martinique', 'Martinik'],
            'MR' => ['Mauritania', 'Moritanya'],
            'MS' => ['Montserrat', 'Montserrat'],
            'MT' => ['Malta', 'Malta'],
            'MU' => ['Mauritius', 'Mauritius'],
            'MV' => ['Maldives', 'Maldivler'],
            'MW' => ['Malawi', 'Malavi'],
            'MX' => ['Mexico', 'Meksika'],
            'MY' => ['Malaysia', 'Malezya'],
            'MZ' => ['Mozambique', 'Mozambik'],
            'NA' => ['Namibia', 'Namibya'],
            'NC' => ['New Caledonia', 'Yeni Kaledonya'],
            'NE' => ['Niger', 'Nijer'],
            'NF' => ['Norfolk Island', 'Norfolk Adası'],
            'NG' => ['Nigeria', 'Nijerya'],
            'NI' => ['Nicaragua', 'Nikaragua'],
            'NL' => ['Netherlands', 'Hollanda'],
            'NO' => ['Norway', 'Norveç'],
            'NP' => ['Nepal', 'Nepal'],
            'NR' => ['Nauru', 'Nauru'],
            'NU' => ['Niue', 'Niue'],
            'NZ' => ['New Zealand', 'Yeni Zelanda'],
            'OM' => ['Oman', 'Umman'],
            'PA' => ['Panama', 'Panama'],
            'PE' => ['Peru', 'Peru'],
            'PF' => ['French Polynesia', 'Fransız Polinezyası'],
            'PG' => ['Papua New Guinea', 'Papua Yeni Gine'],
            'PH' => ['Philippines', 'Filipinler'],
            'PK' => ['Pakistan', 'Pakistan'],
            'PL' => ['Poland', 'Polonya'],
            'PM' => ['Saint Pierre and Miquelon', 'Saint Pierre ve Miquelon'],
            'PN' => ['Pitcairn', 'Pitcairn'],
            'PR' => ['Puerto Rico', 'Porto Riko'],
            'PS' => ['Palestine', 'Filistin'],
            'PT' => ['Portugal', 'Portekiz'],
            'PW' => ['Palau', 'Palau'],
            'PY' => ['Paraguay', 'Paraguay'],
            'QA' => ['Qatar', 'Katar'],
            'RE' => ['Réunion', 'Réunion'],
            'RO' => ['Romania', 'Romanya'],
            'RS' => ['Serbia', 'Sırbistan'],
            'RU' => ['Russia', 'Rusya'],
            'RW' => ['Rwanda', 'Ruanda'],
            'SA' => ['Saudi Arabia', 'Suudi Arabistan'],
            'SB' => ['Solomon Islands', 'Solomon Adaları'],
            'SC' => ['Seychelles', 'Seyşeller'],
            'SD' => ['Sudan', 'Sudan'],
            'SE' => ['Sweden', 'İsveç'],
            'SG' => ['Singapore', 'Singapur'],
            'SH' => ['Saint Helena', 'Saint Helena'],
            'SI' => ['Slovenia', 'Slovenya'],
            'SJ' => ['Svalbard and Jan Mayen', 'Svalbard ve Jan Mayen'],
            'SK' => ['Slovakia', 'Slovakya'],
            'SL' => ['Sierra Leone', 'Sierra Leone'],
            'SM' => ['San Marino', 'San Marino'],
            'SN' => ['Senegal', 'Senegal'],
            'SO' => ['Somalia', 'Somali'],
            'SR' => ['Suriname', 'Surinam'],
            'SS' => ['South Sudan', 'Güney Sudan'],
            'ST' => ['São Tomé and Príncipe', 'São Tomé ve Príncipe'],
            'SV' => ['El Salvador', 'El Salvador'],
            'SX' => ['Sint Maarten', 'Sint Maarten'],
            'SY' => ['Syria', 'Suriye'],
            'SZ' => ['Eswatini', 'Esvatini'],
            'TC' => ['Turks and Caicos Islands', 'Turks ve Caicos Adaları'],
            'TD' => ['Chad', 'Çad'],
            'TF' => ['French Southern Territories', 'Fransız Güney Toprakları'],
            'TG' => ['Togo', 'Togo'],
            'TH' => ['Thailand', 'Tayland'],
            'TJ' => ['Tajikistan', 'Tacikistan'],
            'TK' => ['Tokelau', 'Tokelau'],
            'TL' => ['Timor-Leste', 'Doğu Timor'],
            'TM' => ['Turkmenistan', 'Türkmenistan'],
            'TN' => ['Tunisia', 'Tunus'],
            'TO' => ['Tonga', 'Tonga'],
            'TR' => ['Türkiye', 'Türkiye'],
            'TT' => ['Trinidad and Tobago', 'Trinidad ve Tobago'],
            'TV' => ['Tuvalu', 'Tuvalu'],
            'TW' => ['Taiwan', 'Tayvan'],
            'TZ' => ['Tanzania', 'Tanzanya'],
            'UA' => ['Ukraine', 'Ukrayna'],
            'UG' => ['Uganda', 'Uganda'],
            'UM' => ['U.S. Outlying Islands', 'ABD Küçük Dış Adaları'],
            'US' => ['United States', 'Amerika Birleşik Devletleri'],
            'UY' => ['Uruguay', 'Uruguay'],
            'UZ' => ['Uzbekistan', 'Özbekistan'],
            'VA' => ['Vatican City', 'Vatikan'],
            'VC' => ['Saint Vincent and the Grenadines', 'Saint Vincent ve Grenadinler'],
            'VE' => ['Venezuela', 'Venezuela'],
            'VG' => ['British Virgin Islands', 'Britanya Virjin Adaları'],
            'VI' => ['U.S. Virgin Islands', 'ABD Virjin Adaları'],
            'VN' => ['Vietnam', 'Vietnam'],
            'VU' => ['Vanuatu', 'Vanuatu'],
            'WF' => ['Wallis and Futuna', 'Wallis ve Futuna'],
            'WS' => ['Samoa', 'Samoa'],
            'YE' => ['Yemen', 'Yemen'],
            'YT' => ['Mayotte', 'Mayotte'],
            'ZA' => ['South Africa', 'Güney Afrika'],
            'ZM' => ['Zambia', 'Zambiya'],
            'ZW' => ['Zimbabwe', 'Zimbabve'],
        ];
    }

    public static function isValid(?string $code): bool
    {
        $code = strtoupper((string) $code);

        return isset(self::all()[$code]);
    }

    public static function codes(): array
    {
        return array_keys(self::all());
    }
}
